////

  Licensed to the Apache Software Foundation (ASF) under one or more
  contributor license agreements.  See the NOTICE file distributed with
  this work for additional information regarding copyright ownership.
  The ASF licenses this file to You under the Apache License, Version 2.0
  (the "License"); you may not use this file except in compliance with
  the License.  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.

////

== Sönke Liebau

* Contributor: Kafka & various others
* PPMC: Training


== Lars Francke

* ASF Member
* Committer: HBase, Hive, (ORC)
* PPMC & Champion: Training


== Both

* Founded https://www.opencore.com[OpenCore] together
* Consultancy focused on the Big Data ecosystem
** Broadly speaking, talk to us if you're interested in learning more
* Based in Germany
* For good beer we can recommend "Gordon Biersch"
** This is "Training" after all
