////

  Licensed to the Apache Software Foundation (ASF) under one or more
  contributor license agreements.  See the NOTICE file distributed with
  this work for additional information regarding copyright ownership.
  The ASF licenses this file to You under the Apache License, Version 2.0
  (the "License"); you may not use this file except in compliance with
  the License.  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.

////

== Current State
* Currently mostly focused on getting up and running
* Create basic tooling
* Get the community going
But we have a lot of ideas where we can take this!

== Ideas for the Future
Imagine your employer asks you to read up on this new product and bring your colleagues up to speed on it.

== What do you do today?
* Check out the GitHub page
* Browse the documentation
* Install it & play around with it
* Create some slides to show your colleagues

== How I Imagine this in the Future (1)
* Check out the GitHub page
* Browse the documentation
* Install & play around with it

== How I Imagine this in the Future (2)
* Go on the Apache Training website and look for modules on this product
** Select the introductory and two advanced modules that you consider of interest
** Include these modules in your presentation
** Add custom intro slides and company specific information
* Compile presentation with your company's CI


==  How I Imagine this in the Future (3)
Success!!

== Content Repository
* Apache Training as a huge content repository for all sorts of training material
** Fully indexed and searchable
** Tagged with meaningful metadata
** Composable
* Nice UI

[NOTE.speaker]
--
* Find icons here: https://fontawesome.com/v4.7.0/icons/
* Color icons by defining CSS styles in apache.css and referencing them with "role"
--

== Metadata
* Product
* Skill Level
* Content
* Duration
* Prerequisites
* ...

== Feedback System
* Collect general and specific feedback at the end of the course
** Trainer
** Material
** ...
* Open system to create surveys and gather responses

== Labs / Hands On Parts
* Generate homepage for practical elements of the training
* Tooling for spinning up VMs in AWS, Azure, GCP, ...
** Provisioning
** Prepping with data
** Whatever else is necessary

